[package]
name = "horn_schunck_rs"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "horn_schunck_rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
env_logger = "0.11.11"
log = "0.4.34"
ndarray = "0.17.2"
nokhwa = { version = "0.10.11", features = ["input-native", "output-wgpu"] }
numpy = "0.28.0"
pollster = "1.0.1"
pyo3 = "0.28.2"
wgpu = "30.0.1"
winit = "0.30.13"
